--
-- PostgreSQL database dump
--

-- Dumped from database version 12.6 (Ubuntu 12.6-1.pgdg18.04+1)
-- Dumped by pg_dump version 13.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP POLICY "NFT update" ON public.nft;
DROP POLICY "NFT select" ON public.nft;
DROP POLICY "NFT insert" ON public.nft;
DROP POLICY "NFT delete" ON public.nft;
ALTER TABLE ONLY public.nft DROP CONSTRAINT nft_pkey;
DROP TABLE public.nft;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: nft; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.nft (
    id integer NOT NULL,
    name character varying,
    description character varying,
    author character varying,
    "backgroundId" integer NOT NULL,
    creator character varying NOT NULL,
    "chainId" smallint NOT NULL,
    "defaultEmotion" character varying
);


ALTER TABLE public.nft OWNER TO supabase_admin;

--
-- Name: nft_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.nft ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nft_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nft nft_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.nft
    ADD CONSTRAINT nft_pkey PRIMARY KEY (id);


--
-- Name: nft NFT delete; Type: POLICY; Schema: public; Owner: supabase_admin
--

CREATE POLICY "NFT delete" ON public.nft FOR DELETE USING (false);


--
-- Name: nft NFT insert; Type: POLICY; Schema: public; Owner: supabase_admin
--

CREATE POLICY "NFT insert" ON public.nft FOR INSERT WITH CHECK (false);


--
-- Name: nft NFT select; Type: POLICY; Schema: public; Owner: supabase_admin
--

CREATE POLICY "NFT select" ON public.nft FOR SELECT USING (true);


--
-- Name: nft NFT update; Type: POLICY; Schema: public; Owner: supabase_admin
--

CREATE POLICY "NFT update" ON public.nft FOR UPDATE USING (false);


--
-- Name: nft; Type: ROW SECURITY; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.nft ENABLE ROW LEVEL SECURITY;

--
-- Name: TABLE nft; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.nft TO postgres;
GRANT ALL ON TABLE public.nft TO anon;
GRANT ALL ON TABLE public.nft TO authenticated;
GRANT ALL ON TABLE public.nft TO service_role;


--
-- Name: SEQUENCE nft_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.nft_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.nft_id_seq TO anon;
GRANT ALL ON SEQUENCE public.nft_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.nft_id_seq TO service_role;


--
-- PostgreSQL database dump complete
--

