/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IQAirdrop, IQAirdropInterface } from "../IQAirdrop";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_qstkAmount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_signature",
        type: "bytes",
      },
    ],
    name: "withdrawLockedQStk",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IQAirdrop__factory {
  static readonly abi = _abi;
  static createInterface(): IQAirdropInterface {
    return new utils.Interface(_abi) as IQAirdropInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IQAirdrop {
    return new Contract(address, _abi, signerOrProvider) as IQAirdrop;
  }
}
