/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IQNFT, IQNFTInterface } from "../IQNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "qstkBalances",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalAssignedQstk",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IQNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IQNFTInterface {
    return new utils.Interface(_abi) as IQNFTInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IQNFT {
    return new Contract(address, _abi, signerOrProvider) as IQNFT;
  }
}
