/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface QNFTSettingsInterface extends ethers.utils.Interface {
  functions: {
    "NFT_SALE_DURATION()": FunctionFragment;
    "PERCENT_MAX()": FunctionFragment;
    "addCharacterPrices(uint256[])": FunctionFragment;
    "addFavCoinPrices(uint256[])": FunctionFragment;
    "addLockOption(uint256,uint256,uint256,uint8)": FunctionFragment;
    "calcMintPrice(uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "characterCount()": FunctionFragment;
    "characterPrices(uint256)": FunctionFragment;
    "favCoinPrices(uint256)": FunctionFragment;
    "favCoinsCount()": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "lockOptionLockDuration(uint256)": FunctionFragment;
    "lockOptions(uint256)": FunctionFragment;
    "lockOptionsCount()": FunctionFragment;
    "mintEndTime()": FunctionFragment;
    "mintFinished()": FunctionFragment;
    "mintPaused()": FunctionFragment;
    "mintStartTime()": FunctionFragment;
    "mintStarted()": FunctionFragment;
    "nonTokenPriceMultiplier()": FunctionFragment;
    "onlyAirdropUsers()": FunctionFragment;
    "pauseMint()": FunctionFragment;
    "qstkPrice()": FunctionFragment;
    "setNonTokenPriceMultiplier(uint256)": FunctionFragment;
    "setOnlyAirdropUsers(bool)": FunctionFragment;
    "setTokenPriceMultiplier(uint256)": FunctionFragment;
    "settings()": FunctionFragment;
    "startMint()": FunctionFragment;
    "tokenPriceMultiplier()": FunctionFragment;
    "unPauseMint()": FunctionFragment;
    "updateCharacterPrice(uint256,uint256)": FunctionFragment;
    "updateFavCoinPrice(uint256,uint256)": FunctionFragment;
    "updateLockOption(uint256,uint256,uint256,uint256,uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "NFT_SALE_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PERCENT_MAX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addCharacterPrices",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addFavCoinPrices",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addLockOption",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calcMintPrice",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "characterCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "characterPrices",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "favCoinPrices",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "favCoinsCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "lockOptionLockDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockOptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockOptionsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintFinished",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintStarted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nonTokenPriceMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onlyAirdropUsers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pauseMint", values?: undefined): string;
  encodeFunctionData(functionFragment: "qstkPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setNonTokenPriceMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOnlyAirdropUsers",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenPriceMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "settings", values?: undefined): string;
  encodeFunctionData(functionFragment: "startMint", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenPriceMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unPauseMint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateCharacterPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFavCoinPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLockOption",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "NFT_SALE_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PERCENT_MAX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCharacterPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addFavCoinPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLockOption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calcMintPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "characterCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "characterPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "favCoinPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "favCoinsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockOptionLockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockOptionsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintFinished",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintStarted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nonTokenPriceMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onlyAirdropUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pauseMint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "qstkPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setNonTokenPriceMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOnlyAirdropUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenPriceMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settings", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "startMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenPriceMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unPauseMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCharacterPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFavCoinPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLockOption",
    data: BytesLike
  ): Result;

  events: {
    "AddCharacterPrices(address,uint256[])": EventFragment;
    "AddFavCoinPrices(address,uint256[])": EventFragment;
    "AddLockOption(address,uint256,uint256,uint256,uint256)": EventFragment;
    "PauseMint(address,uint256)": EventFragment;
    "SetNonTokenPriceMultiplier(address,uint256)": EventFragment;
    "SetTokenPriceMultiplier(address,uint256)": EventFragment;
    "StartMint(address,uint256)": EventFragment;
    "UnpauseMint(address,uint256)": EventFragment;
    "UpdateCharacterPrice(address,uint256,uint256)": EventFragment;
    "UpdateFavCoinPrice(address,uint256,uint256)": EventFragment;
    "UpdateLockOption(address,uint256,uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddCharacterPrices"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AddFavCoinPrices"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AddLockOption"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PauseMint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetNonTokenPriceMultiplier"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetTokenPriceMultiplier"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StartMint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnpauseMint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateCharacterPrice"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateFavCoinPrice"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateLockOption"): EventFragment;
}

export class QNFTSettings extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: QNFTSettingsInterface;

  functions: {
    NFT_SALE_DURATION(overrides?: CallOverrides): Promise<[BigNumber]>;

    PERCENT_MAX(overrides?: CallOverrides): Promise<[BigNumber]>;

    addCharacterPrices(
      _characterPrices: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addFavCoinPrices(
      _favCoinPrices: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addLockOption(
      _minAmount: BigNumberish,
      _maxAmount: BigNumberish,
      _lockDuration: BigNumberish,
      _discount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    calcMintPrice(
      _characterId: BigNumberish,
      _favCoinId: BigNumberish,
      _lockOptionId: BigNumberish,
      _lockAmount: BigNumberish,
      _freeAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    characterCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    characterPrices(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    favCoinPrices(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    favCoinsCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    initialize(
      _settings: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lockOptionLockDuration(
      _lockOptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    lockOptions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, number] & {
        minAmount: BigNumber;
        maxAmount: BigNumber;
        lockDuration: BigNumber;
        discount: number;
      }
    >;

    lockOptionsCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    mintEndTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    mintFinished(overrides?: CallOverrides): Promise<[boolean]>;

    mintPaused(overrides?: CallOverrides): Promise<[boolean]>;

    mintStartTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    mintStarted(overrides?: CallOverrides): Promise<[boolean]>;

    nonTokenPriceMultiplier(overrides?: CallOverrides): Promise<[BigNumber]>;

    onlyAirdropUsers(overrides?: CallOverrides): Promise<[boolean]>;

    pauseMint(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    qstkPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    setNonTokenPriceMultiplier(
      _nonTokenPriceMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOnlyAirdropUsers(
      _onlyAirdropUsers: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTokenPriceMultiplier(
      _tokenPriceMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    settings(overrides?: CallOverrides): Promise<[string]>;

    startMint(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokenPriceMultiplier(overrides?: CallOverrides): Promise<[BigNumber]>;

    unPauseMint(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateCharacterPrice(
      _characterId: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateFavCoinPrice(
      _favCoinId: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateLockOption(
      _lockOptionId: BigNumberish,
      _minAmount: BigNumberish,
      _maxAmount: BigNumberish,
      _lockDuration: BigNumberish,
      _discount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  NFT_SALE_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

  PERCENT_MAX(overrides?: CallOverrides): Promise<BigNumber>;

  addCharacterPrices(
    _characterPrices: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addFavCoinPrices(
    _favCoinPrices: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addLockOption(
    _minAmount: BigNumberish,
    _maxAmount: BigNumberish,
    _lockDuration: BigNumberish,
    _discount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  calcMintPrice(
    _characterId: BigNumberish,
    _favCoinId: BigNumberish,
    _lockOptionId: BigNumberish,
    _lockAmount: BigNumberish,
    _freeAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  characterCount(overrides?: CallOverrides): Promise<BigNumber>;

  characterPrices(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  favCoinPrices(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  favCoinsCount(overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    _settings: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lockOptionLockDuration(
    _lockOptionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  lockOptions(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, number] & {
      minAmount: BigNumber;
      maxAmount: BigNumber;
      lockDuration: BigNumber;
      discount: number;
    }
  >;

  lockOptionsCount(overrides?: CallOverrides): Promise<BigNumber>;

  mintEndTime(overrides?: CallOverrides): Promise<BigNumber>;

  mintFinished(overrides?: CallOverrides): Promise<boolean>;

  mintPaused(overrides?: CallOverrides): Promise<boolean>;

  mintStartTime(overrides?: CallOverrides): Promise<BigNumber>;

  mintStarted(overrides?: CallOverrides): Promise<boolean>;

  nonTokenPriceMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

  onlyAirdropUsers(overrides?: CallOverrides): Promise<boolean>;

  pauseMint(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  qstkPrice(overrides?: CallOverrides): Promise<BigNumber>;

  setNonTokenPriceMultiplier(
    _nonTokenPriceMultiplier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOnlyAirdropUsers(
    _onlyAirdropUsers: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTokenPriceMultiplier(
    _tokenPriceMultiplier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  settings(overrides?: CallOverrides): Promise<string>;

  startMint(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokenPriceMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

  unPauseMint(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateCharacterPrice(
    _characterId: BigNumberish,
    _price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateFavCoinPrice(
    _favCoinId: BigNumberish,
    _price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateLockOption(
    _lockOptionId: BigNumberish,
    _minAmount: BigNumberish,
    _maxAmount: BigNumberish,
    _lockDuration: BigNumberish,
    _discount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    NFT_SALE_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

    PERCENT_MAX(overrides?: CallOverrides): Promise<BigNumber>;

    addCharacterPrices(
      _characterPrices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    addFavCoinPrices(
      _favCoinPrices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    addLockOption(
      _minAmount: BigNumberish,
      _maxAmount: BigNumberish,
      _lockDuration: BigNumberish,
      _discount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    calcMintPrice(
      _characterId: BigNumberish,
      _favCoinId: BigNumberish,
      _lockOptionId: BigNumberish,
      _lockAmount: BigNumberish,
      _freeAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    characterCount(overrides?: CallOverrides): Promise<BigNumber>;

    characterPrices(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    favCoinPrices(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    favCoinsCount(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(_settings: string, overrides?: CallOverrides): Promise<void>;

    lockOptionLockDuration(
      _lockOptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lockOptions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, number] & {
        minAmount: BigNumber;
        maxAmount: BigNumber;
        lockDuration: BigNumber;
        discount: number;
      }
    >;

    lockOptionsCount(overrides?: CallOverrides): Promise<BigNumber>;

    mintEndTime(overrides?: CallOverrides): Promise<BigNumber>;

    mintFinished(overrides?: CallOverrides): Promise<boolean>;

    mintPaused(overrides?: CallOverrides): Promise<boolean>;

    mintStartTime(overrides?: CallOverrides): Promise<BigNumber>;

    mintStarted(overrides?: CallOverrides): Promise<boolean>;

    nonTokenPriceMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    onlyAirdropUsers(overrides?: CallOverrides): Promise<boolean>;

    pauseMint(overrides?: CallOverrides): Promise<void>;

    qstkPrice(overrides?: CallOverrides): Promise<BigNumber>;

    setNonTokenPriceMultiplier(
      _nonTokenPriceMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setOnlyAirdropUsers(
      _onlyAirdropUsers: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenPriceMultiplier(
      _tokenPriceMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    settings(overrides?: CallOverrides): Promise<string>;

    startMint(overrides?: CallOverrides): Promise<void>;

    tokenPriceMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    unPauseMint(overrides?: CallOverrides): Promise<void>;

    updateCharacterPrice(
      _characterId: BigNumberish,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateFavCoinPrice(
      _favCoinId: BigNumberish,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateLockOption(
      _lockOptionId: BigNumberish,
      _minAmount: BigNumberish,
      _maxAmount: BigNumberish,
      _lockDuration: BigNumberish,
      _discount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    AddCharacterPrices(
      owner?: string | null,
      prices?: null
    ): TypedEventFilter<
      [string, BigNumber[]],
      { owner: string; prices: BigNumber[] }
    >;

    AddFavCoinPrices(
      owner?: string | null,
      mintPrices?: null
    ): TypedEventFilter<
      [string, BigNumber[]],
      { owner: string; mintPrices: BigNumber[] }
    >;

    AddLockOption(
      owner?: string | null,
      minAmount?: null,
      maxAmount?: null,
      lockDuration?: null,
      discount?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        owner: string;
        minAmount: BigNumber;
        maxAmount: BigNumber;
        lockDuration: BigNumber;
        discount: BigNumber;
      }
    >;

    PauseMint(
      owner?: string | null,
      pausedAt?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { owner: string; pausedAt: BigNumber }
    >;

    SetNonTokenPriceMultiplier(
      owner?: string | null,
      nonTokenPriceMultiplier?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { owner: string; nonTokenPriceMultiplier: BigNumber }
    >;

    SetTokenPriceMultiplier(
      owner?: string | null,
      tokenPriceMultiplier?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { owner: string; tokenPriceMultiplier: BigNumber }
    >;

    StartMint(
      owner?: string | null,
      startedAt?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { owner: string; startedAt: BigNumber }
    >;

    UnpauseMint(
      owner?: string | null,
      unPausedAt?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { owner: string; unPausedAt: BigNumber }
    >;

    UpdateCharacterPrice(
      owner?: string | null,
      characterId?: BigNumberish | null,
      price?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { owner: string; characterId: BigNumber; price: BigNumber }
    >;

    UpdateFavCoinPrice(
      owner?: string | null,
      favCoinId?: null,
      price?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { owner: string; favCoinId: BigNumber; price: BigNumber }
    >;

    UpdateLockOption(
      owner?: string | null,
      lockOptionId?: BigNumberish | null,
      minAmount?: null,
      maxAmount?: null,
      lockDuration?: null,
      discount?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        owner: string;
        lockOptionId: BigNumber;
        minAmount: BigNumber;
        maxAmount: BigNumber;
        lockDuration: BigNumber;
        discount: BigNumber;
      }
    >;
  };

  estimateGas: {
    NFT_SALE_DURATION(overrides?: CallOverrides): Promise<BigNumber>;

    PERCENT_MAX(overrides?: CallOverrides): Promise<BigNumber>;

    addCharacterPrices(
      _characterPrices: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addFavCoinPrices(
      _favCoinPrices: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addLockOption(
      _minAmount: BigNumberish,
      _maxAmount: BigNumberish,
      _lockDuration: BigNumberish,
      _discount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    calcMintPrice(
      _characterId: BigNumberish,
      _favCoinId: BigNumberish,
      _lockOptionId: BigNumberish,
      _lockAmount: BigNumberish,
      _freeAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    characterCount(overrides?: CallOverrides): Promise<BigNumber>;

    characterPrices(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    favCoinPrices(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    favCoinsCount(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _settings: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lockOptionLockDuration(
      _lockOptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lockOptions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lockOptionsCount(overrides?: CallOverrides): Promise<BigNumber>;

    mintEndTime(overrides?: CallOverrides): Promise<BigNumber>;

    mintFinished(overrides?: CallOverrides): Promise<BigNumber>;

    mintPaused(overrides?: CallOverrides): Promise<BigNumber>;

    mintStartTime(overrides?: CallOverrides): Promise<BigNumber>;

    mintStarted(overrides?: CallOverrides): Promise<BigNumber>;

    nonTokenPriceMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    onlyAirdropUsers(overrides?: CallOverrides): Promise<BigNumber>;

    pauseMint(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    qstkPrice(overrides?: CallOverrides): Promise<BigNumber>;

    setNonTokenPriceMultiplier(
      _nonTokenPriceMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOnlyAirdropUsers(
      _onlyAirdropUsers: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTokenPriceMultiplier(
      _tokenPriceMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    settings(overrides?: CallOverrides): Promise<BigNumber>;

    startMint(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokenPriceMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    unPauseMint(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateCharacterPrice(
      _characterId: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateFavCoinPrice(
      _favCoinId: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateLockOption(
      _lockOptionId: BigNumberish,
      _minAmount: BigNumberish,
      _maxAmount: BigNumberish,
      _lockDuration: BigNumberish,
      _discount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    NFT_SALE_DURATION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PERCENT_MAX(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addCharacterPrices(
      _characterPrices: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addFavCoinPrices(
      _favCoinPrices: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addLockOption(
      _minAmount: BigNumberish,
      _maxAmount: BigNumberish,
      _lockDuration: BigNumberish,
      _discount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    calcMintPrice(
      _characterId: BigNumberish,
      _favCoinId: BigNumberish,
      _lockOptionId: BigNumberish,
      _lockAmount: BigNumberish,
      _freeAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    characterCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    characterPrices(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    favCoinPrices(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    favCoinsCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _settings: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lockOptionLockDuration(
      _lockOptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lockOptions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lockOptionsCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintEndTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintFinished(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintPaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintStartTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintStarted(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nonTokenPriceMultiplier(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onlyAirdropUsers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pauseMint(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    qstkPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setNonTokenPriceMultiplier(
      _nonTokenPriceMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOnlyAirdropUsers(
      _onlyAirdropUsers: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTokenPriceMultiplier(
      _tokenPriceMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    settings(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    startMint(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokenPriceMultiplier(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unPauseMint(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateCharacterPrice(
      _characterId: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateFavCoinPrice(
      _favCoinId: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateLockOption(
      _lockOptionId: BigNumberish,
      _minAmount: BigNumberish,
      _maxAmount: BigNumberish,
      _lockDuration: BigNumberish,
      _discount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
